services:
  - type: web
    name: pizzacapucino-mvp
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npx prisma db push --accept-data-loss && node prisma/fix-settings.js && node prisma/seed.js && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 12h
      - key: ADMIN_COOKIE_NAME
        value: admin_token
      - key: CORS_ORIGIN
        sync: false
      - key: RESTAURANT_NAME
        value: Pizza Capucino
      - key: PUBLIC_UPI_QR_URL
        sync: false
      - key: WHATSAPP_BOOKING_NUMBER
        sync: false
      - key: ADMIN_SEED_USERNAME
        sync: false
      - key: ADMIN_SEED_PASSWORD
        sync: false
      - key: ADMIN_SEED_EMAIL
        sync: false
      - key: ADMIN_SEED_FULL_NAME
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM_EMAIL
        sync: false
      - key: SMTP_FROM_NAME
        value: Pizza Capucino
      - key: CLOUDINARY_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
